name = "blanksheet-worker"
main = "cloudflare-worker.ts"
compatibility_date = "2024-12-01"

kv_namespaces = [
  { binding = "LOGS", id = "6ff7545ff6434d388526329f26c4a0a7", preview_id = "118ec715ad994de5837d2000ca6b39d0" }
]