/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as DevAnalyticsRouteImport } from './routes/dev/analytics'
import { Route as IndexTsxBakRouteImport } from './routes/index.tsx.bak'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAnalyticsRoute = DevAnalyticsRouteImport.update({
  id: '/dev/analytics',
  path: '/dev/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexTsxBakRoute = IndexTsxBakRouteImport.update({
  id: '/index/tsx/bak',
  path: '/index/tsx/bak',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/analytics': typeof DevAnalyticsRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/index/tsx/bak': typeof IndexTsxBakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/analytics': typeof DevAnalyticsRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/index/tsx/bak': typeof IndexTsxBakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/analytics': typeof DevAnalyticsRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/index/tsx/bak': typeof IndexTsxBakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/analytics' | '/p/$projectId' | '/index/tsx/bak'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/analytics' | '/p/$projectId' | '/index/tsx/bak'
  id: '__root__' | '/' | '/dev/analytics' | '/p/$projectId' | '/index/tsx/bak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevAnalyticsRoute: typeof DevAnalyticsRoute
  PProjectIdRoute: typeof PProjectIdRoute
  IndexTsxBakRoute: typeof IndexTsxBakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/analytics': {
      id: '/dev/analytics'
      path: '/dev/analytics'
      fullPath: '/dev/analytics'
      preLoaderRoute: typeof DevAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/tsx/bak': {
      id: '/index/tsx/bak'
      path: '/index/tsx/bak'
      fullPath: '/index/tsx/bak'
      preLoaderRoute: typeof IndexTsxBakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevAnalyticsRoute: DevAnalyticsRoute,
  PProjectIdRoute: PProjectIdRoute,
  IndexTsxBakRoute: IndexTsxBakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
